---
- name: Deploy App
  hosts: app
  become: true

  tasks:
    - name: fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      notify: reload puma
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
