---
- name: Deploy App
  hosts: app
  vars:
    deploy_user: ubuntu
  become: true

  tasks:
    - name: fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith

    - name: bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"
      notify: reload puma
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
